#!/bin/bash

# Delete build artifacts if they exist
[ -d dist ] && rm -r dist

# Setup a new sandbox
cabal sandbox delete
cabal sandbox init

# Install dependencies, configure and build
cabal install -j --dependencies --enable-tests -O2
cabal configure --enable-tests -O2
cabal -j build
cabal test
